apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Workflows-Quickstart
  title: Create a New GitHub Repository with Jira Integration
  description: Creates a new GitHub Repository and logs a Jira issue
  annotations:
    accountIdentifier: <+account.identifier>
    orgIdentifier: <+variable.account.orgIdentifier>
    projectIdentifier: <+variable.account.projectIdentifier>
spec:
  owner: service.owner
  type: service
  parameters:
    - title: Fill in the repo and Jira details
      required:
        - github_org_name
        - github_repo_name
        - jira_project_key
        - jira_issue_summary
      properties:
        github_org_name:
          title: GitHub Organization
          type: string
          description: Name of the org where you want to add the new repository
        github_repo_name:
          title: Repository Name
          type: string
          description: Name the new repository that you want to create
        jira_project_key:
          title: Jira Project Key
          type: string
          description: Jira project where the issue should be created (e.g., IDP)
        jira_issue_summary:
          title: Jira Issue Summary
          type: string
          description: Summary of the Jira issue to be created
        jira_issue_description:
          title: Jira Issue Description
          type: string
          description: Detailed description of the Jira issue (optional)
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken       

  steps:
    - id: trigger
      name: Onboarding a New GitHub Repository
      action: trigger:harness-custom-pipeline
      input:
        url: "https://laxmiharness.pr2.harness.io/ng/account/<+account.identifier>/idp-admin/orgs/<+variable.account.orgIdentifier>/projects/<+variable.account.projectIdentifier>/pipelines/GitHub_Repo_Onboarding/pipeline-studio/?storeType=INLINE&stageId=IDP&sectionId=EXECUTION"
        inputset:
          github_org: ${{ parameters.github_org_name }}
          github_repo: ${{ parameters.github_repo_name }}
        apikey: ${{ parameters.token }}

    - id: create-jira-ticket
      name: Create Jira Issue
      action: jira:create-issue
      input:
        project: ${{ parameters.jira_project_key }}
        issuetype: "Task"
        summary: ${{ parameters.jira_issue_summary }}
        description: ${{ parameters.jira_issue_description || 'Automated issue for GitHub repo onboarding.' }}
        labels:
          - onboarding
          - github
          - automation

  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
      - title: Jira Issue
        url: ${{ steps.create-jira-ticket.output.issueUrl }}
